name: test-supabase-cache

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: supabase/setup-cli@fix-v299-latest-archive
        with:
          version: latest

      - run: supabase start
      - run: supabase status
      - run: supabase stop
